### ISSUE TITLE
Solvent model water

### ISSUE THREAD

**Issue by PodewitzLab** [PodewitzLab/PyConSolv#27]
Default solvent model is SPC/E but we would like an option to change it to tip3p. There is no restart file for the equilibration.

**Comment by Lapsis-glitch** [comment]
Default is now changed to TIP3P, options for OPC and TIP4PEW have been added with the WaterOPC and WaterTIP4PEW keywords. see 47ca1120a8af5699965572dfdcbc96317deae4df
