### ISSUE TITLE
Topology errors with v 1.0.3.1

### ISSUE THREAD

**Issue by tanoury1** [PodewitzLab/PyConSolv#44]
Hi,
Thank you for the updates to the code.  I tried the latest version (1.0.3) using the attached xyz file (two acetate anions) and THF as solvent.  I chose Ca2+ as the counterion.

Everything went as expected until step 4 of the equilibration.  I got the error below and more details in 04.out (attached)
  ------------------------------------------------------------------------------------------------------------------    
Tleap completed successfully 

Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
Equlibration step 1 completed successfully

Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
Equlibration step 2 completed successfully

Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
Equlibration step 3 completed successfully

STOP PMEMD Terminated Abnormally!
Equlibration step 4 failed!

Something went wrong, please check your input/output

    ############################################
    ######             WARNING            ######
    ######      Calculation failed at:    ######
    ######         Equilibration          ######
    ############################################
    
If error stems from grid changes, you can modify the input file for the offending step and restart the equilibration with the provided restart script in
 /cluster/home/tanoury/PyConSolv/tests/CaOAc2/equilibration
-------------------------------------------------------------------------------------------------------------------------------------------------------

This was a mismatch in the atom numbering between LIG_solv.prmtop and 03.rst7.  I followed the instructions in http://archive.ambermd.org/201308/0340.html, and ran the file containing the 4 lines below using cpptraj.

parm LIG_solv.prmtop 
trajin 03.rst7
fixatomorder outprefix reorder
trajout reorder.rst7 restart

Then, I renamed reorder.LIG_solv.prmtop and reorder.rst7, as LIG_solv.prmtop and 03.rst7, respectively.

I ran restart_equil.sh, which completed the equilibration step successfully, but did not populate the simulation directory with the required files.  I had to change pyconsolv.restart from 'tleap' to 'equilibration', then rerun the PyConSolv calculation with the original commandline arguments and instantly got the correct files in the simulation directory.

When starting the simulation run, I got the same error message.  (sim-01.out, attached)

I fixed this the same way as before with:

parm LIG_solv.prmtop 
trajin eq.rst7
fixatomorder outprefix reorder
trajout reorder.rst7 restart

I was able to start the simulation, but the got the error below....and that's where I stopped.

gpu_neighbor_list_setup :: Small box detected, with <= 2 cells in one or more 
                           dimensions.  The current GPU code has been deemed
                           unsafe for these situations.  Please alter the
                           cutoff to increase the number of hash cells, make
                           use of the CPU code, or (if absolutely necessary)
                           run pmemd.cuda with the -AllowSmallBox flag.  This
                           behavior will be corrected in a forthcoming patch.

Jerry
[04.out.txt](https://github.com/PodewitzLab/PyConSolv/files/13225953/04.out.txt)
[sim-01.out.txt](https://github.com/PodewitzLab/PyConSolv/files/13225954/sim-01.out.txt)

**Comment by tanoury1** [comment]
Oops, forgot to add my structure file.  
[Acetate_dimer.xyz.txt](https://github.com/PodewitzLab/PyConSolv/files/13227000/Acetate_dimer.xyz.txt)

**Comment by Lapsis-glitch** [comment]
Hi Jerry,
Thanks for the heads-up. I will look into fixing this and get back to you. 
Cheers,
Radu

**Comment by Lapsis-glitch** [comment]
The issue resulted from tleap not dealing with multiple non-covalently bound structures correctly. It is now fixes with #49
