### ISSUE TITLE
FileNotFoundError with orca_freq.molden.chg 

### ISSUE THREAD

**Issue by Foly93** [PodewitzLab/PyConSolv#45]
Hi I am trying to run the testfiles supplied in the git repository:

```bash
conda activate PyConSolv
pyconsolv input.xyz -p 1
```

However, I am running into the following error:

```bash

[.... Printed Messages stating that everything is going alright ....]

MCPB.py step 1 completed successfully

/home/luisvollmers/anaconda3/envs/PyConSolv/lib/python3.10/site-packages/pymsmt/mcpb/gene_final_frcmod_file.py:490: RuntimeWarning: invalid value encountered in scalar divide
  vecUN = array([i/norm(vecUNp) for i in vecUNp]) #vecUN is the vector
MCPB.py step 2 completed successfully

Changing charges
Traceback (most recent call last):
  File "/home/luisvollmers/anaconda3/envs/PyConSolv/bin/pyconsolv", line 8, in <module>
    sys.exit(main())
  File "/home/luisvollmers/anaconda3/envs/PyConSolv/lib/python3.10/site-packages/PyConSolv/pyconsolv.py", line 59, in main
    conf.run(charge= args.charge , method = args.method, basis = args.basis , dsp = args.dispersion , cpu = args.cpu ,
  File "/home/luisvollmers/anaconda3/envs/PyConSolv/lib/python3.10/site-packages/PyConSolv/ConfGen.py", line 827, in run
    if self.MCPB_script() == 0:
  File "/home/luisvollmers/anaconda3/envs/PyConSolv/lib/python3.10/site-packages/PyConSolv/ConfGen.py", line 547, in MCPB_script
    self.xyz.createFinalMol2(self.inputpath)
  File "/home/luisvollmers/anaconda3/envs/PyConSolv/lib/python3.10/site-packages/PyConSolv/misc/inputparser.py", line 516, in createFinalMol2
    self.readRESP(path + '/orca_calculations')
  File "/home/luisvollmers/anaconda3/envs/PyConSolv/lib/python3.10/site-packages/PyConSolv/misc/inputparser.py", line 601, in readRESP
    f = open(filepath, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/luisvollmers/henmount/zfs/s01/z01/home/lvollmers/projects/000-Miscellaneous/14-LuisNTPParametrisation/_modelling/03_TUMUC_ProtocollwMethanol/02_bonds_anglesPyConSolcTryout/orca_calculations/freq/orca_freq.molden.chg'
```
Any idea what could go wrong here? I am using the following versions within the required packages:

ambertools: 23
openmpi: 5.0.0
multiwfn: 3.8
orca: 5.0.4
python: 3.10

numpy.__version__ '1.26.0'
pandas.__version__ '2.1.3'
matplotlib.__version__ '3.8.2'
rdkit.__version__ '2023.09.1'
parmed.__version__ '4.2.2'

**Comment by Lapsis-glitch** [comment]
Hi!
Thanks for the report!

I tried to reproduce the error on my end using the same setup, with the difference that my orca is linked to openmpi 4.1.1 (ORCA should be linked to 4.1.1 according to the devs, but might run fine with 5.0.0) , but was not able to.

I noticed that the path you are running the calculation from is quite deep. This can cause some issues with Multiwfn and might be related to why the calculation failed.

Can you check if the file "orca_calculations/freq/orca_freq.molden.chg" exists?
If not, can you generate it by navigating to the orca_calculations/freq folder and run Multiwfn < multiwfn.input?
If this works, can you retry the calculation from a folder in your home directory?

Best,
Radu

**Comment by Foly93** [comment]
Hi Radu,

1. I have checked, there is no file with that filename/path
2. I tried ```bash Multiwfn < multiwfn.input``` and it produced an output with a very similar name: ```bash orca_freq.chg```

I tried running pyconsolv and it resulted in the same error, but I tried simply ```bash cp orca_freq.chg orca_freq.molden.chg``` and the pyconsolv ran! 

So I guess that solves my issue.

Best, Luis

**Comment by Lapsis-glitch** [comment]
Hi Luis,

Can you possibly run pyconsolv again on the test file in a new folder to get the error and then zip it and send me the files?

I would like to dig a bit deeper into this and see what happens that causes the error.

Did you also try to run pyconsolv in a new folder in your home directory? Does it also cause an error there?

Thanks,
Radu

**Comment by Foly93** [comment]
Hi Radu, 

I have created an empty folder in my home directory (```bash ~/```) with just ```bash input.xyz``` in it and ran ```bash pyconsolv input.xyz -p 1```. Same error as before. 

The zip file is in attached. I am using ubuntu jammy jellyfish.

Cheers,

Luis
[pyconsolv_error.zip](https://github.com/PodewitzLab/PyConSolv/files/13448486/pyconsolv_error.zip)

**Comment by bioc-talmazra** [comment]
Hi Luis,

Thanks for the files! I looked into it and it seems like there might have been some changes in the Multiwfn code. My version is Version 3.8(dev), release date: 2022-Dec-1 and yours is Version 3.8(dev), release date: 2023-Nov-7.

It generates the .chg file correctly, It just saves it under a different name (orca_freq.chg instead of orca_freq.molden.chg). I will have a fix for this soon and will close this issue when the new release is out on pypi.

Thanks for the help in troubleshooting and let me know if you encounter any other problems.

Best,
Radu

**Comment by Lapsis-glitch** [comment]
Hi Luis,

Thanks for the files! I looked into it and it seems like there might have been some changes in the Multiwfn code. My version is Version 3.8(dev), release date: 2022-Dec-1 and yours is Version 3.8(dev), release date: 2023-Nov-7.

It generates the .chg file correctly, It just saves it under a different name (orca_freq.chg instead of orca_freq.molden.chg). I will have a fix for this soon and will close this issue when the new release is out on pypi.

Thanks for the help in troubleshooting and let me know if you encounter any other problems.

Best,
Radu

**Comment by Foly93** [comment]
Hi Radu,

Ah I see. Thank you for the feedback and your help! 

Best,

Luis
