### ISSUE TITLE
MCPB error when prepare 68Ga-DOTATATE

### ISSUE THREAD

**Issue by AzraelXu** [PodewitzLab/PyConSolv#46]
Dear  Lapsis-glitch
   I hope this message finds you well. I am writing to seek assistance regarding an issue I encountered while using PyConsolv to generate the conformation of 68Ga-DOTATATE, as illustrated in the attached figure.

![image](https://github.com/PodewitzLab/PyConSolv/assets/71536738/c5a47dbd-f82e-434f-a2a5-b2f3830a3071)

The problem arises when I attempt to run MCPB, as it returns an error. I am uncertain about the specific cause of the error and would greatly appreciate your guidance on how to resolve it.

The command I employed for PyConsolv is as follows:

`pyconsolv ga_dotanoc.xyz -c 0 -m BP86 -b def2-SVP -d D4 -s Water -mult 2 -p 32`

I would be grateful if you could review the provided information and advise me on any adjustments or additional steps needed to successfully address the MCPB error.

![image](https://github.com/PodewitzLab/PyConSolv/assets/71536738/34386457-b572-4a8e-b176-5c6380195bcb)

Thank you very much for your time and assistance. I look forward to hearing from you soon.

Best regards,

Xu

***Below, I have included the XYZ file that I utilized:

190       
obj01
N 38.758999 41.243000 27.584000
C 39.051998 41.280998 29.034000
O 40.834999 41.393002 25.813000
C 37.470001 40.638000 27.237000
N 41.301998 40.230000 28.698999
O 40.132000 43.340000 25.080999
C 40.576000 41.409000 29.188999
N 38.476002 39.240002 25.358999
O 38.535000 39.348000 21.770000
C 37.368000 40.167000 25.806999
N 39.912998 37.909000 27.659000
O 43.326000 41.202000 30.572001
C 41.101002 39.081001 29.576000
O 36.793999 39.189999 23.125000
C 38.320000 37.806000 25.716000
O 41.591000 38.948002 25.917999
C 40.019001 38.084999 29.121000
O 41.757000 37.021999 24.997999
C 38.569000 37.477001 27.202999
C 39.058998 42.507000 26.895000
C 40.147999 42.445000 25.864000
C 42.691002 40.455002 28.292999
C 38.936001 39.568001 24.014999
C 43.624001 40.708000 29.481001
C 38.000000 39.292000 22.867001
C 41.022999 37.124001 27.186001
C 41.610001 37.720001 25.955000
H 38.495998 42.105000 29.497000
H 38.588001 40.362000 29.414000
H 36.737999 41.435001 27.419001
H 37.069000 39.841000 27.874001
H 40.817001 42.317001 28.622999
H 40.838001 41.597000 30.238001
H 37.318001 41.039001 25.143999
H 36.359001 39.787998 25.601999
H 41.016998 39.354000 30.636000
H 42.008999 38.486000 29.733000
H 37.285999 37.535000 25.469000
H 38.933998 37.094002 25.150999
H 39.075001 38.397999 29.583000
H 40.347000 37.182999 29.652000
H 37.835999 38.058998 27.775999
H 38.289001 36.436001 27.408001
H 42.937000 41.334000 27.684000
H 43.173000 39.667999 27.698999
H 39.882999 39.040001 23.847000
H 39.217999 40.626999 23.976999
H 40.653999 36.116001 26.955999
H 41.794998 37.041000 27.961000
H 39.367001 43.332001 27.549999
H 38.233002 42.821999 26.246000
N 44.901001 40.625000 29.202999
C 46.007000 41.049000 30.066999
C 46.145000 40.122002 31.285999
O 46.432999 38.936001 31.087999
C 47.235001 41.119999 29.259001
C 48.563000 41.097000 30.049999
C 49.026001 42.214001 30.775999
C 49.466999 40.053001 29.893999
C 50.148998 42.147999 31.530001
C 50.743999 40.125999 30.518999
C 51.075001 41.119999 31.430000
H 45.101002 40.394001 28.240000
H 45.848999 42.051998 30.462000
H 47.269001 40.243999 28.611000
H 47.145000 42.034000 28.673000
H 48.326000 43.034000 30.834000
H 49.265999 39.243999 29.208000
H 50.332001 42.991001 32.181000
H 51.477001 39.358002 30.320000
H 52.098000 41.171001 31.771999
N 45.804001 40.516998 32.483002
C 45.646999 39.799999 33.657001
C 44.326000 39.938999 34.208000
O 43.949001 41.027000 34.685001
C 46.876999 39.992001 34.669998
S 48.494999 39.944000 34.129002
H 45.917999 41.514000 32.590000
H 45.558998 38.768002 33.319000
H 46.745998 40.945000 35.183998
H 46.842999 39.226002 35.444000
N 43.537998 38.853001 34.220001
C 42.154999 38.849998 34.729000
C 41.740002 37.639000 35.597000
O 41.866001 36.466999 35.313999
C 41.205002 39.025002 33.590000
C 39.758999 39.075001 34.005001
C 39.098000 40.249001 34.464001
C 38.966000 37.945999 34.083000
C 37.751999 40.320999 34.694000
C 37.587002 37.915001 34.429001
C 36.946999 39.147999 34.660999
O 35.694000 39.127998 35.140999
H 43.898998 37.988998 33.841000
H 42.035000 39.688999 35.415001
H 41.469002 40.008999 33.202000
H 41.294998 38.358002 32.733002
H 39.710999 41.133999 34.558998
H 39.438000 37.000999 33.855000
H 37.277000 41.276001 34.863998
H 37.077000 36.963001 34.397999
H 35.563999 39.918999 35.667999
C 40.945000 37.173000 37.999001
N 41.248001 38.051998 36.799999
O 42.521000 37.966999 39.702000
C 39.745998 37.837002 38.700001
N 38.762001 35.234001 41.120998
C 39.237000 36.995998 39.848999
C 39.313999 35.636002 39.887001
C 38.203999 36.280998 41.811001
C 37.462002 36.248001 43.016998
C 36.985001 37.465000 43.562000
C 37.306000 38.675999 42.874001
C 38.025002 38.693001 41.701000
C 38.521999 37.480000 41.074001
C 42.110001 37.069000 38.956001
H 41.104000 39.027000 37.022999
H 40.654999 36.248001 37.500999
H 40.115002 38.778000 39.108002
H 38.955002 37.960999 37.959999
H 39.834999 35.092999 39.112999
H 38.582001 34.255001 41.290001
H 37.168999 35.273998 43.379002
H 36.425999 37.490002 44.485001
H 36.985001 39.632999 43.257000
H 38.386002 39.611000 41.261002
N 42.606998 35.837002 39.036999
C 43.776001 35.562000 39.870998
C 45.067001 34.976002 39.199001
O 46.014999 34.473000 39.817001
C 43.428001 34.675999 41.035000
C 42.155998 35.005001 41.825001
C 42.187000 34.568001 43.348999
C 40.935001 34.974998 44.103001
N 40.910999 34.341999 45.418999
H 42.256001 35.101002 38.441002
H 44.216999 36.519001 40.148998
H 43.279999 33.636002 40.743999
H 44.296001 34.546001 41.681999
H 41.883999 36.060001 41.831001
H 41.293999 34.542999 41.341999
H 42.362000 33.494999 43.425999
H 43.011002 35.103001 43.819000
H 40.825001 36.058998 44.112999
H 40.062000 34.597000 43.570000
H 39.993000 34.391998 45.835999
H 41.060001 33.342999 45.416000
H 41.535999 34.845001 46.033001
N 45.063000 34.973000 37.849998
C 46.231998 34.703999 37.018002
C 46.105999 35.445000 35.709000
O 45.090000 35.886002 35.384998
C 46.458000 33.244999 36.754002
C 45.373001 32.568001 35.785000
O 47.685001 32.909000 36.229000
H 44.208000 35.179001 37.354000
H 47.089001 35.118000 37.549000
H 46.285000 32.695000 37.679001
H 48.237999 32.817001 37.007999
H 45.563000 31.495001 35.831001
H 44.384998 32.903000 36.099998
H 45.495998 32.949001 34.771999
N 47.176998 35.549999 34.868999
C 47.294998 36.276001 33.580002
C 46.873001 35.431000 32.349998
O 47.331001 34.346001 32.097000
C 48.737999 36.882999 33.412998
S 49.025002 38.140999 34.743999
H 48.051998 35.251999 35.276001
H 46.638000 37.145000 33.606998
H 49.540001 36.144001 33.396000
H 48.577000 37.441002 32.491001
C 45.905998 35.348000 30.028999
N 46.133999 35.995998 31.327999
O 43.613998 35.353001 30.528000
C 44.577999 34.610001 29.907000
O 47.249001 37.058998 28.763000
C 44.625000 33.187000 30.448999
C 46.039001 36.360001 28.813999
H 46.087002 37.005001 31.308001
H 45.967999 35.743000 27.919001
H 45.208000 37.061001 28.886000
H 47.397999 37.606998 29.537001
H 46.721001 34.641998 29.870001
H 44.264000 34.660000 28.864000
H 43.664001 32.679001 30.371000
H 45.029999 33.123001 31.459000
H 45.277000 32.624001 29.781000
H 43.826000 35.435001 31.461000
Ga 40.112000 39.860001 26.650999

**Comment by Lapsis-glitch** [comment]
Hi Xu,

Thanks for reaching out, I will try to replicate the issue on my end and get back to you soon.

Best,
Radu

**Comment by AzraelXu** [comment]
Hi Radu,

Thanks for your prompt response. I appreciate your efforts in looking into the issue. If there's any additional information you need from my end, please feel free to reach out anytime.

Best regards,
Xu

**Comment by AzraelXu** [comment]
Hi Radu,

Thank you for the update. I appreciate your efforts in addressing the issue. I eagerly await your next message and look forward to the fix in the upcoming release.

Best regards,
Xu

**Comment by Lapsis-glitch** [comment]
Hi Xu,
Version 1.0.5 is out now and should have fixed the error you were encountering. Can you check if it works for you?
Thanks and best regards,
Radu
