### ISSUE TITLE
Using PyConSolv for QM/MM jobs

### ISSUE THREAD

**Issue by tanoury1** [PodewitzLab/PyConSolv#52]
Hi,
Have you considered adding support for QM/MM jobs in PyConSolv?  

All the best,
Jerry

**Comment by Lapsis-glitch** [comment]
Hi Jerry,
Yes, initial support for performing the final energy ranking with a QM/MM optimization calculation is implemented in 1.0.5, which should be releasing at the end of this week. 
Performing a full on QM/MM MD to get better sampling is also something that I considered and might implement down the road.
Did you have anything particular in mind?

Best regards,
Radu

**Comment by tanoury1** [comment]
Hi Radu,
I've been interested being able to run a final optimiation on the entire solute/solvent system, which QM/MM would fit nicely into.  Also, looking forward to the QM/MM MD support.  That would be really nice.

Jerry

**Comment by Lapsis-glitch** [comment]
Hi Jerry,
Version 1.0.5 is now out and it allows you to perform QM/MM optimizations and single point calculations when evaluation the simulation. You need to pass the **-qmmm** flag when running the analysis and follow the prompts. Be aware that when you are choosing the QM/MM atoms, they are provided in the format orca expects, which means that if you give it **0:10**, 11 atoms will be selected for the QM part, from 0 to 10, including 10.

Let me know if you encounter any issues with it or if you have any suggestions for improvements.

Best,
Radu

**Comment by tanoury1** [comment]
Hi Radu,
This sounds wonderful.  I'll be giving it a go this coming week.  I'll let
you know how it goes.

Jerry

**Comment by tanoury1** [comment]
I got an attribute error (see below).  I just removed 'ts=args.ts' from line 64.  The job is running as expected.

Traceback (most recent call last):
  File "/cluster/home/tanoury/miniconda3/envs/PyConSolv/bin/pyconsolv", line 8, in <module>
    sys.exit(main())
  File "/cluster/home/tanoury/miniconda3/envs/PyConSolv/lib/python3.10/site-packages/PyConSolv/pyconsolv.py", line 64, in main
    solvent = args.solvent, multiplicity = args.multiplicity, engine = args.engine, opt = args.noopt, box = args.box, ts = args.ts )
AttributeError: 'Namespace' object has no attribute 'ts'

Jerry

**Comment by Lapsis-glitch** [comment]
Hi Jerry,
Thanks for pointing it out, this probably got through from another feature that's in the works.
I'll have a fix for it out tomorrow.
Thanks for trying it out! Let me know if anything else pops up and you feel like some features are still missing.

Best,
Radu

**Comment by Lapsis-glitch** [comment]
This has been fixed with 1.0.6.2
