### ISSUE TITLE
Error is writing LIG.mol2 file during MCPB step.

### ISSUE THREAD

**Issue by tanoury1** [PodewitzLab/PyConSolv#55]
Hi again Radu,
With the system I am studying (2-aminopyridine reaction with N2O3 in water), there seems to be an error in the LIG.mol2 file that is written during the mcpb step.  The file, attached, is trying to form a bond between atoms 27 and 30, but there are only 21 atoms in the LIG system.  The error is in the tleap.log file.  I've also attached the Orca optimized structure (to save you the time of running the initial QM optimization).  In my system, the charges are:
2-aminopyridine: 0
NO2: -1
NO: +1

I get the error with versions 1.0.4 and 1.0.5.
[LIG.mol2.txt](https://github.com/PodewitzLab/PyConSolv/files/14009402/LIG.mol2.txt)
[orca_opt.xyz.txt](https://github.com/PodewitzLab/PyConSolv/files/14009403/orca_opt.xyz.txt)
[tleap.log.txt](https://github.com/PodewitzLab/PyConSolv/files/14009404/tleap.log.txt)

Jerry

**Comment by bioc-talmazra** [comment]
Hi Jerry,
I will have a look at it today to see what goes wrong and try to fix it.

Thanks,
Radu

**Comment by Lapsis-glitch** [comment]
Hi Jerry,

I will have a look at the issue today and try to fix it.

Thanks,
Radu

**Comment by Lapsis-glitch** [comment]
Hi Jerry,
The fix for this is now live in 1.0.6

Best,
Radu

**Comment by tanoury1** [comment]
Awesome. I’ll give it a try today.

**Comment by Lapsis-glitch** [comment]
Hi Jerry,
I will close this issue if it's resolved for you as well.

Best,
Radu

**Comment by Lapsis-glitch** [comment]
Issue resolved with merge #56
