### ISSUE TITLE
Setting up a default restrained sim

### ISSUE THREAD

**Issue by maberl1** [PodewitzLab/PyConSolv#62]
Oy,
please give the -rst flag the possibility to run with the atomids as arguments which would then set up the restrained sim with default values thus bypassing the dialogue.
Thanks <3

**Comment by Lapsis-glitch** [comment]
The restrained simulation method is already implemented, but it is geared towards freezing specific internal coordinates of the system.
For restraining  coordinates on the cartesian level, such as the restraints required for a GIST analysis, I can implement a separate keyword.

**Comment by maberl1** [comment]
Smooth
