### ISSUE TITLE
Cartesian coordinate swapping on last line of fakechk.fchk

### ISSUE THREAD

**Issue by flblanc** [PodewitzLab/PyConSolv#64]
Dear PyConSolv dev, 

I may have found a bug in the `Faker` class after noticing that it produced a `.fchk` file in which the X and Z coordinates of the last atom were swapped. I tracked it down to the `writeout` method of `Faker`,specifically in the instruction following the `if len(list_f) % 5 != 0:` command. The way it is written, `list_f` is looped over from end to beginning, causing the last line to be written backwards. Here is a workaround which seems to work:

```python
if len(list_f) % 5 != 0:
		for i in range(len(list_f) % 5)[::-1]: # Loop over list backwards
			f.write(' {:14E}'.format(np.double(list_f[-(i + 1)]) * factor))
```
that is, the issue is solved by looping in reverse over `range(len(list_f) % 5)`. 
Could you please have a look?

**Comment by Lapsis-glitch** [comment]
Thanks for the report, I will have a look at this asap.

**Comment by flblanc** [comment]
Great ! In passing, thanks a lot for your code, it is very useful for my research.

**Comment by Lapsis-glitch** [comment]
Super happy to hear that it's useful ! By the way, if you find it could use some extra features, don't hesitate to open a new issue.
